name: wrangling 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.2
  - jupyterlab
  - ipykernel
  - pyarrow=14.0.2
  - ydata-profiling=4.8.3 
  - ipywidgets=8.1.3 
  - scikit-learn=1.5.1
  - missingno=0.5.2
  - thefuzz=0.22.1
  - great_expectations=0.18.18
  - pip
  - pip:
    - anonymizedf==1.0.1
